name: CI

on:
  push:
    branches: [ 2x-dev, 3x-dev ]
    paths-ignore:
      - 'coverage/**'
      - '*.md'
      - '*.txt'

env: 
  dotnet-version: 3.1.201
  source-url: "https://nuget.pkg.github.com/${{github.repository_owner}}/index.json"

jobs:
  build-windows:
    strategy:
      fail-fast: false 
      matrix: 
        configuration: ['FAKE_XRM_EASY_9', 'FAKE_XRM_EASY_365', 'FAKE_XRM_EASY_2016','FAKE_XRM_EASY_2015','FAKE_XRM_EASY_2013','FAKE_XRM_EASY']

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core for Actual Source
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.dotnet-version }}
 
    - name: Disable local packages feed
      run: dotnet nuget disable source "local-packages"

    - name: Enable GitHub packages feed
      run: dotnet nuget enable source github
      
    - name: Build
      run: pwsh ./build.ps1 -configuration ${{matrix.configuration}} -targetFramework 'all'
      env: 
        NUGET_USERNAME: DynamicsValue
        NUGET_TOKEN: ${{ secrets.PACKAGES_TOKEN }} 

  sonar:
    needs: build-windows
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '11' # The JDK version to make available on the path.
        java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
        architecture: x64 # (x64 or x86) - defaults to x64

    - name: Setup .NET Core for Actual Source
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.dotnet-version }}
 
    - name: Disable local packages feed
      run: dotnet nuget disable source "local-packages"

    - name: Enable GitHub packages feed
      run: dotnet nuget enable source github 

    - name: Quality Gate
      run: pwsh ./sonar-scan.ps1 -sonarProjectName "fake-xrm-easy-code-activities" -sonarProjectKey ${{ secrets.SONAR_PROJECT_KEY }} -sonarLogin ${{ secrets.SONAR_TOKEN }} -sonarOrganisation "dynamicsvalue"
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NUGET_USERNAME: DynamicsValue
        NUGET_TOKEN: ${{ secrets.PACKAGES_TOKEN }}


  pack-push:
    needs:  [build-windows, sonar]
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core for Actual Source
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.dotnet-version }}
 
      - name: Disable local packages feed
        run: dotnet nuget disable source "local-packages"

      - name: Enable GitHub packages feed
        run: dotnet nuget enable source github 

      - name: Build
        run: pwsh ./build.ps1 -targetFrameworks 'all'
        env: 
          NUGET_USERNAME: DynamicsValue
          NUGET_TOKEN: ${{ secrets.PACKAGES_TOKEN }}

      - name: Pack Src
        run: pwsh ./pack-src.ps1 -targetFrameworks 'all' -versionSuffix "ci.${{ github.head_ref }}${{ github.run_number }}"
        env: 
          NUGET_USERNAME: DynamicsValue
          NUGET_TOKEN: ${{ secrets.PACKAGES_TOKEN }}

      - name: Push Src
        run: nuget.exe push .\nupkgs\FakeXrmEasy.CodeActivities.*.nupkg -Source ${{ env.source-url }}
        env: 
          NUGET_USERNAME: DynamicsValue
          NUGET_AUTH_TOKEN: ${{ github.token }}
          NUGET_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Pack Tests
        run: pwsh ./pack-tests.ps1 -targetFrameworks 'all' -versionSuffix "ci.${{ github.head_ref }}${{ github.run_number }}"
        env: 
          NUGET_USERNAME: DynamicsValue
          NUGET_TOKEN: ${{ secrets.PACKAGES_TOKEN }}

      - name: Push Tests
        run: nuget.exe push .\nupkgs\FakeXrmEasy.CodeActivitiesTests.*.nupkg -Source ${{ env.source-url }}
        env: 
          NUGET_USERNAME: DynamicsValue
          NUGET_AUTH_TOKEN: ${{ github.token }}
          NUGET_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    
   
